import { useState } from 'react';
import { Link } from 'react-router-dom';
import Header from '../components/Header';
import Footer from '../components/Footer';
import ThreeDViewer from '../components/ThreeDViewer';

const EXAMPLES = [
  {
    id: 1, name: 'Compact 2BHK',
    desc: '2 bedrooms, kitchen, bathroom — standard residential layout',
    rooms: 5, walls: 12, area: '387 m²',
    modelUrl: '/outputs/example_2bhk.obj',
    tag: 'Residential', tagColor: '#dbeafe', tagText: '#1d4ed8',
    details: ['Living / Hall', 'Master Bedroom', 'Bedroom', 'Kitchen', 'Bathroom'],
  },
  {
    id: 2, name: 'Open Floor Plan',
    desc: 'Large living space with minimal interior partitions',
    rooms: 4, walls: 10, area: '310 m²',
    modelUrl: '/outputs/example_open.obj',
    tag: 'Modern', tagColor: '#dcfce7', tagText: '#15803d',
    details: ['Living / Hall', 'Master Bedroom', 'Bedroom', 'Kitchen', 'Bathroom'],
  },
  {
    id: 3, name: 'Multi-Room Layout',
    desc: '3 bedrooms, 2 bathrooms, dining room — family home',
    rooms: 8, walls: 18, area: '420 m²',
    modelUrl: '/outputs/multi_room_v2.obj',
    tag: 'Family', tagColor: '#fef3c7', tagText: '#92400e',
    details: ['Living / Hall', 'Master Bedroom', 'Bedroom', 'Kitchen', 'Bathroom', 'Bedroom', 'Dining Room', 'Bathroom'],
  },
];

const DarkCTA = () => (
  <div className="rounded-3xl p-10 text-center relative overflow-hidden"
    style={{ background: 'linear-gradient(135deg,#0c1a3a,#0f2460,#1a3a7a)', boxShadow: '0 20px 60px rgba(12,26,58,.35)' }}>
    <div className="absolute inset-0 pointer-events-none"
      style={{ backgroundImage: 'linear-gradient(rgba(147,197,253,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(147,197,253,.07) 1px,transparent 1px)', backgroundSize: '40px 40px' }} />
    <div className="relative z-10">
      <h2 className="heading mb-3" style={{ color: 'white' }}>Try it with your own floor plan</h2>
      <p className="text-sm mb-6 max-w-md mx-auto" style={{ color: 'rgba(191,219,254,.7)', lineHeight: 1.7 }}>
        Upload any floor plan image and get a full 3D model in seconds.
      </p>
      <Link to="/app" className="inline-flex items-center gap-2 font-bold px-7 py-3 rounded-full text-sm"
        style={{ background: '#2563eb', color: 'white', boxShadow: '0 4px 20px rgba(37,99,235,.5)' }}
        onMouseEnter={e => { e.currentTarget.style.background='#1d4ed8'; e.currentTarget.style.transform='translateY(-2px)'; }}
        onMouseLeave={e => { e.currentTarget.style.background='#2563eb'; e.currentTarget.style.transform='none'; }}>
        Upload & Analyse
        <svg width="13" height="13" viewBox="0 0 14 14" fill="none"><path d="M3 7h8M8 4l3 3-3 3" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>
      </Link>
    </div>
  </div>
);

export default function ExampleGalleryPage() {
  const [active, setActive] = useState(0);
  const ex = EXAMPLES[active];

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh' }}>
      <Header />
      <main className="max-w-6xl mx-auto px-6 pt-32 pb-20 space-y-12">

        <div className="anim-fade-up">
          <span className="badge badge-blue mb-4">Example Gallery</span>
          <h1 className="heading" style={{ color: 'var(--text-1)' }}>Browse 3D Model Examples</h1>
          <p className="mt-2 max-w-lg text-sm" style={{ color: 'var(--text-2)', lineHeight: 1.7 }}>
            Real 3D models generated by ASIS AI from floor plan images. Click any example to explore it interactively.
          </p>
        </div>

        <div className="grid lg:grid-cols-[260px_1fr] gap-6 anim-fade-up anim-delay-1">
          {/* Selector */}
          <div className="space-y-3">
            <p className="label mb-1">Select Model</p>
            {EXAMPLES.map((e, i) => (
              <button key={e.id} onClick={() => setActive(i)} className="w-full text-left rounded-2xl p-4 transition-all"
                style={{ background: active===i ? 'var(--accent-lt)' : 'white', border: `1.5px solid ${active===i ? 'var(--accent)' : 'var(--border)'}`, boxShadow: active===i ? '0 0 0 3px rgba(29,78,216,.10)' : 'none' }}>
                <div className="flex items-start justify-between gap-2 mb-1.5">
                  <p className="font-semibold text-sm" style={{ color: 'var(--text-1)' }}>{e.name}</p>
                  <span className="text-xs font-semibold px-2 py-0.5 rounded-full flex-shrink-0" style={{ background: e.tagColor, color: e.tagText }}>{e.tag}</span>
                </div>
                <p className="text-xs mb-2" style={{ color: 'var(--text-3)' }}>{e.desc}</p>
                <div className="flex gap-3 text-xs" style={{ color: 'var(--text-2)' }}>
                  <span>🏠 {e.rooms} rooms</span><span>📏 {e.walls} walls</span>
                </div>
              </button>
            ))}
            <Link to="/app" className="btn-primary w-full justify-center" style={{ fontSize: '0.82rem', marginTop: '8px' }}>
              Upload Your Own
              <svg width="12" height="12" viewBox="0 0 14 14" fill="none"><path d="M3 7h8M8 4l3 3-3 3" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>
            </Link>
          </div>

          {/* Viewer */}
          <div className="space-y-4">
            <div className="dark-panel overflow-hidden" style={{ height: 460 }}>
              <ThreeDViewer isLoading={false} previewUrl={ex.modelUrl} />
            </div>
            <div className="grid grid-cols-3 gap-3">
              {[['Rooms', ex.rooms], ['Walls', ex.walls], ['Area', ex.area]].map(([l, v]) => (
                <div key={l} className="card p-4 text-center" style={{ background: 'white' }}>
                  <p className="text-xl font-bold" style={{ color: 'var(--accent)' }}>{v}</p>
                  <p className="label mt-1">{l}</p>
                </div>
              ))}
            </div>
            <div className="card p-4" style={{ background: 'white' }}>
              <p className="label mb-3">Detected Rooms</p>
              <div className="flex flex-wrap gap-2">
                {ex.details.map(r => (
                  <span key={r} className="text-xs font-medium px-3 py-1 rounded-full" style={{ background: 'var(--bg-2)', color: 'var(--accent)', border: '1px solid var(--border)' }}>{r}</span>
                ))}
              </div>
            </div>
          </div>
        </div>

        <DarkCTA />
      </main>
      <Footer />
    </div>
  );
}
